---
sbom_work_dir: "{{ sbom_host_output_dir }}"
sbom_grype_sbom_file: ""
sbom_grype_helper_dir: /usr/local/lib/secops-sbom
sbom_actionable_only: true
sbom_grype_extra_args: ""
sbom_grype_distro: ""
sbom_target_os_distro: ""
sbom_grype_slim_output: true
sbom_grype_timeout: ""

sbom_grype_timeout_default: 600
